pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Build') {
            environment {
                DOCKER_REGISTRY = 'https://registry.hub.docker.com' // URL du registre Docker
            }
            steps {
                script {
                    sh "git archive --output=app/build.tar.gz --format=tar HEAD ./app"
                    dir('app') {
                        dockerImage.withRegistry("${DOCKER_REGISTRY}", credentials('docker-account')) {
                            def dockerImage = docker.build('veilles-mathisrome-fr', '-f Dockerfile.prod .')
                            dockerImage.push()
                        }
                    }
                }
            }
        }

        stage('Deliver') {
            agent {
                label 'deploy'
            }
            steps {
                sh "docker compose -f docker-compose.prod.yml up -d"
            }
        }
    }
}
