pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Build') {
            steps {
                sh "cd app"
                script {
                    def dockerImage = docker.build('veilles-mathisrome-fr', '-f Dockerfile.prod .')
                    dockerImage.push()
                }
            }
        }

        stage('Deliver') {
            agent {
                label 'deploy'
            }
            steps {
                sh "docker compose -f docker-compose.prod.yml up -d"
            }
        }
    }
}
